name: Provision Terraform Cloud Resume Infrastructure

on:
  push:
    branches:
      - main 

jobs:
  terraform:
    name: 'Terraform Plan & Apply'
    runs-on: ubuntu-latest
    permissions:
      id-token: write 
      contents: read 

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }} 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # OIDC federation
      - name: Configure AWS Credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }} 

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -out=tfplan

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve tfplan